version: "3.9"

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    ports:
        - "9200:9200"
        - "9300:9300"
    environment:
        - discovery.type=single-node
  app:
    container_name: app
    depends_on:
        - elasticsearch      
    build: .
    ports:
        - "8080:8080"
